// Example
//{id:'one', name:'Serpenski Triangle', path:'../0_Sandbox/1_Example', alts:['one', 'two'] },
// to add a seperator:
//{id:'', name:'Popular'},

var apps = 
[
{id:'LengthContraction', name:'Length Contraction', path:'../0_Sandbox/LengthContraction', alts:['one'] },
{id:'PathIntegral', name:'Path Integral', path:'../0_Sandbox/PathIntegral', alts:['one'] },
{id:'GravityLens', name:'Gravity Lens', path:'../0_Sandbox/GravityLens', alts:['one'] },
{id:'', name:'Relativity'},
{id:'SpeedOfLight', name:'SpeedOfLight', path:'../Apps/SpeedOfLight', alts:['one'] },
{id:'TwinParadox', name:'TwinParadox', path:'../Apps/TwinParadox', alts:['one'] },
{id:'', name:'Quantum Physics'},
{id:'DelayedChoice', name:'DelayedChoice', path:'../Apps/DelayedChoice', alts:['one'] },
{id:'TwoSlit', name:'TwoSlit', path:'../Apps/TwoSlit', alts:['one'] },
{id:'QuantumEraser', name:'QuantumEraser', path:'../Apps/QuantumEraser', alts:['one'] },
{id:'Entangled', name:'Entangled', path:'../Apps/Entangled', alts:['one'] },
{id:'', name:'Physics'},
{id:'Spring2', name:'Spring2', path:'../Apps/Spring2', alts:['one'] },
{id:'Spring', name:'Spring', path:'../Apps/Spring', alts:['one'] },
{id:'', name:'Maths'},
{id:'MandelbrotFractal', name:'Mandelbrot Fractal', path:'../Apps/MandelbrotFractal', alts:['SierpinskiTriangle'] },
{id:'SierpinskiTriangle', name:'Sierpinski Triangle', path:'../Apps/SierpinskiTriangle', alts:['FractalFern', 'MandelbrotFractal'] },
{id:'LSystem', name:'L-System', path:'../Apps/L-System', alts:['GeneticTree'] },
{id:'GameOfLife', name:'Game of Life & Gravity Waves', path:'../Apps/GameOfLife', alts:['one'] },
{id:'Wolfram', name:'Wolfram Cellular Automaton', path:'../Apps/Wolfram', alts:['one'] },
{id:'', name:'Evolution'},
{id:'GeneticTree', name:'Genetic Tree', path:'../Apps/GeneticTree', alts:['LSystem'] },
{id:'FractalFern', name:'Fractal Fern', path:'../Apps/FractalFern', alts:['SierpinskiTriangle'] },
{id:'BodyPlan2D', name:'Body Plan 2D', path:'../Apps/BodyPlan2D', alts:['BodyPlan3D'] },
{id:'BodyPlan3D', name:'Body Plan 3D', path:'../Apps/BodyPlan3D', alts:['BodyPlan2D'] },
{id:'BlindWatchmaker', name:'Blind Watchmaker', path:'../Apps/BlindWatchmaker', alts:['one'] },
{id:'', name:'AI'},
{id:'Clippy', name:'Clippy', path:'../Apps/Clippy', alts:['one'] },
{id:'Edge', name:'Edge', path:'../Apps/Edge', alts:['one'] },
{id:'Scan', name:'Scan', path:'../Apps/Scan', alts:['Example'] },
{id:'DeepakChopraOpera', name:'Deepak Chopra Opera', path:'../Apps/DeepakChopraOpera', alts:['Say'] },
{id:'', name:'General'},
{id:'FishEye', name:'Fish Eye', path:'../Apps/FishEye', alts:[] },
{id:'Say', name:'Say', path:'../Apps/Say', alts:['DeepakChopraOpera'] },
{id:'FingerWrite', name:'FingerWrite', path:'../Apps/FingerWrite', alts:['one'] },
{id:'RecogniseLetter', name:'RecogniseLetter', path:'../Apps/RecogniseLetter', alts:['one'] },
{id:'Cosmos', name:'Cosmos', path:'../Apps/Cosmos', alts:['Example'] },
{id:'DerrenBrownMemory', name:'Derren Brown Memory', path:'../Apps/DerrenBrownMemory', alts:['one'] },
{id:'Kaleidoscope', name:'Kaleidoscope', path:'../Apps/Kaleidoscope', alts:['one'] }, 
{id:'myCalendar', name:'myCalendar', path:'../0_Sandbox/myCalendar', alts:['one'] },
{id:'xTalk', name:'xTalk', path:'../0_Sandbox/xTalk', alts:['one'] },
{id:'', name:'Others'},
{id:'Example', name:'Example', path:'../0_Sandbox/1_Example', alts:['Template', 'FishEye', 'MandelbrotFractal'] },
{id:'HarveyBay', name:'Harvey Bay', path:'../Apps/HarveyBay', alts:['one'] },
{id:'TreeJump', name:'Tree Jump', path:'../Apps/TreeJump', alts:['one'] },
{id:'', name:'In progress...'},
{id:'Morse', name:'Morse', path:'../0_Sandbox/Morse', alts:['one'] },
{id:'iRing', name:'iRing', path:'../0_Sandbox/iRing', alts:['one'] },
{id:'Biomorph', name:'Biomorph', path:'../0_Sandbox/Biomorph', alts:['one'] },
{id:'Plankton', name:'Plankton', path:'../0_Sandbox/Plankton', alts:['one'] },
{id:'BridgeBid', name:'BridgeBid', path:'../0_Sandbox/BridgeBid', alts:['one'] },
{id:'Filter', name:'Filter', path:'../0_Sandbox/Filter', alts:['one'] },
{id:'Predator', name:'Predator', path:'../0_Sandbox/Predator', alts:['one'] },
{id:'', name:'Template'},
{id:'Template', name:'Template', path:'../0_Sandbox/0_Template', alts:['Example'] }
];